### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by rockchalkwushock**
This begins fixing the footer to match the designs, obviously not finished. I wanted some feedback on the positioning of the banner elements in the mobile viewport. Where do I find the symbols for the bottom section?

### CODE REVIEW

**Comment by rockchalkwushock** [comment]
They are just placeholders for the moment. I'm using `css-grid` and needed to visualize where things were. I will fill them in with the related content for those areas.

**Comment by MoonTahoe** [comment]
It looks good. I'll try to find those images but don't worry about them. We can always add them on the final scrub. If you put the content inside of the grid then I'll pull this one in.

**Comment by rockchalkwushock** [comment]
@MoonTahoe 

Here is the finished footer. The only thing I'm not entirely sure of is how to put in the line above the "View Full Schedule" link. I had to go in and update the `<SocialIcons />`. Should we make that component programmatic? I'm not sure where else if is being used in the end product.

**Comment by MoonTahoe** [comment]
Looks Great! Thanks!

**Pull request merged**
